clinched_auto_bids = {"ACC": None,
              "America East": None,
              "American Athletic": None,
              "Atlantic 10": None,
              "Atlantic Sun": None,
              "Big 12": None,
              "Big East": None,
              "Big South": None,
              "Big Ten": None,
              "Big West": None,
              "Colonial Athletic": None,
              "Conference USA": None,
              "Horizon League": None,
              "Ivy League": None,
              "MAAC": None,
              "MEAC": 'FLORIDA A&M',
              "Mid-American": None,
              "Missouri Valley": None,
              "Mountain West": None,
              "Northeast": None,
              "Ohio Valley": None,
              "Pac-12": None,
              "Patriot League": None,
              "SEC": None,
              "Southern": None,
              "Southland": None,
              "Sun Belt": None,
              "SWAC": None,
              "The Summit League": None,
              "West Coast": None,
              "Western Athletic": None}
