clinched_auto_bids = {"ACC": None,
                      "America East": 'STONY BROOK',
                      "American Athletic": None,
                      "Atlantic 10": 'FORDHAM',
                      "ASUN": None,
                      "Big 12": None,
                      "Big East": None,
                      "Big South": 'CAMPBELL',
                      "Big Ten": None,
                      "Colonial Athletic": None,
                      "Big West": None,
                      "Conference USA": None,
                      "Horizon League": 'UIC',
                      "Ivy League": 'HARVARD',
                      "MAAC": None,
                      "MEAC": 'FLORIDA A&M',
                      "Mid-American": None,
                      "Missouri Valley": None,
                      "Mountain West": None,
                      "Northeast": None,
                      "Ohio Valley": None,
                      "Pac-12": None,
                      "Patriot League": 'ARMY',
                      "SEC": None,
                      "Southern": None,
                      "Southland": None,
                      "Sun Belt": None,
                      "SWAC": 'SOUTHERN',
                      "The Summit League": None,
                      "West Coast": None,
                      "Western Athletic": None}
